[package]
name = "rcmpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.20.3"
regex = "1.10.3"

[lib]
name = "rcmpy"
path = "lib.rs"
