
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CODE COMMENTcode : code COMMENT\n            | code CODE\n            | COMMENT\n            | CODE'
    
_lr_action_items = {'COMMENT':([0,1,2,3,4,5,],[2,4,-3,-4,-1,-2,]),'CODE':([0,1,2,3,4,5,],[3,5,-3,-4,-1,-2,]),'$end':([1,2,3,4,5,],[0,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> code","S'",1,None,None,None),
  ('code -> code COMMENT','code',2,'p_code','comment_cleaner.py',25),
  ('code -> code CODE','code',2,'p_code','comment_cleaner.py',26),
  ('code -> COMMENT','code',1,'p_code','comment_cleaner.py',27),
  ('code -> CODE','code',1,'p_code','comment_cleaner.py',28),
]
